name: home_balance_flutter
description: "Home Balance App for shared house management."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8 
  intl: ^0.19.0 
  firebase_core: ^2.13.0
  firebase_analytics: ^10.5.0
  cloud_firestore: ^4.9.0 # Firestore
  firebase_storage: ^11.2.0 # Storage 
  fl_chart: ^0.63.0  # Pie Chart Library
  cupertino_icons: ^1.0.8
  google_fonts: ^5.1.0
  google_sign_in: ^5.4.0
  firebase_auth: ^4.16.0
  uuid: ^3.0.6
  flutter_localizations:
    sdk: flutter  # Localization support


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/clean.jpg
    - assets/images/dishwasher.jpg
    - assets/images/food.jpg
    - assets/images/food2.jpg
    - assets/images/change_pwd_logo.png
    - assets/images/pwd.png
    - assets/images/sign_in.png
    - assets/images/splash_screen_logo.png
    - assets/images/google_icon.png

