name: home_balance_flutter
description: "Home Balance App for shared house management."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter 
  firebase_core: ^2.15.0
  firebase_analytics: ^10.5.0
  fl_chart: ^0.63.0   # Pie Chart Library
  cupertino_icons: ^1.0.8
  google_fonts: ^5.1.0
  google_sign_in: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/clean.jpg
    - assets/images/dishwasher.jpg
    - assets/images/food.jpg
    - assets/images/food2.jpg
    - assets/images/change_pwd_logo.png
    - assets/images/lock_logo.png
    - assets/images/sign_in_logo.png
    - assets/images/splash_screen_logo.png
    - assets/images/google_logo.png
