// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY_fDOIVEZuMlAAxzWfFMxX3qRmBlayqk',
    appId: '1:622851109037:web:02c39f0333b533ccadd624',
    messagingSenderId: '622851109037',
    projectId: 'home-balance-flutter',
    authDomain: 'home-balance-flutter.firebaseapp.com',
    storageBucket: 'home-balance-flutter.firebasestorage.app',
    measurementId: 'G-WT4H2PQQ4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-o0AaY_AMZEB-iDECBY7UjbKQ3LSX2Eo',
    appId: '1:622851109037:android:28f4bb50ab4745aaadd624',
    messagingSenderId: '622851109037',
    projectId: 'home-balance-flutter',
    storageBucket: 'home-balance-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUkAJ0E5qeTiSYO3Ud2xAZWXYyaUP9I4o',
    appId: '1:622851109037:ios:622c8929ce168aebadd624',
    messagingSenderId: '622851109037',
    projectId: 'home-balance-flutter',
    storageBucket: 'home-balance-flutter.firebasestorage.app',
    iosBundleId: 'com.example.homeBalanceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUkAJ0E5qeTiSYO3Ud2xAZWXYyaUP9I4o',
    appId: '1:622851109037:ios:622c8929ce168aebadd624',
    messagingSenderId: '622851109037',
    projectId: 'home-balance-flutter',
    storageBucket: 'home-balance-flutter.firebasestorage.app',
    iosBundleId: 'com.example.homeBalanceFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY_fDOIVEZuMlAAxzWfFMxX3qRmBlayqk',
    appId: '1:622851109037:web:63c7ae97cafe4e9aadd624',
    messagingSenderId: '622851109037',
    projectId: 'home-balance-flutter',
    authDomain: 'home-balance-flutter.firebaseapp.com',
    storageBucket: 'home-balance-flutter.firebasestorage.app',
    measurementId: 'G-CSZNKM2XJB',
  );
}
